### ISSUE TITLE
Mod this for JGMaker IDEX Printer

### ISSUE THREAD

**Issue by rdagijones** [Kruze17/Magprobe-HX#1]
How difficult do you think it would be to modify the code to use this probe on a JGMaker Artist D Pro? This is an Ender style printer body with dual extruders. I will be using klipper firmware. I would need the servo mount and arm to release and pick up the probe from the left of the build plate. I know that I will need to model and adapt some of the STL files to work on my printer. Would it be as simple as modifying the klipper macro (magprobe.cfg) to use another location?

**Comment by Kruze17** [comment]
Yes, I had made the macro in such a way that it is adaptable for any printer. You can simply change macro according to your needs. It is well commented for all the details. Still if you have any issues you can reply here.
